src/app.py
from flask import Flask, render_template

from src.common.database import Database

app = Flask(__name__)
app.config.from_object('src.config')
app.secret_key = "123"

@app.before_first_request
def init_db():
    Database.initialize()

@app.route('/')
def home():
    return render_template('home.jinja2')

from src.models.users.views import user_blueprint
from src.models.stores.views import store_bluprint
from src.models.alerts.views import alert_blueprint

app.register_blueprint(user_blueprint, url_prefix = "/users")
app.register_blueprint(store_bluprint, url_prefix = "/stores")
app.register_blueprint(alert_blueprint, url_prefix = "/alerts")

src/models/alerts/views.py
from flask import Blueprint, render_template, request, session, redirect, url_for

from src.models.alerts.alert import Alert
from src.models.items.item import Item
import src.models.users.decorators as UserDecorators

alert_blueprint = Blueprint('alerts', __name__)

@UserDecorators.login_required
@alert_blueprint.route('/new', methods = ['POST', 'GET'])
def create_alert():
    if request.method == 'POST':
        name = request.form['alert_name']
        url = request.form['item_url']
        price_limit = float(request.form['price_limit'])
        item = Item(name, url)
        item.save_to_mongo()
        alert = Alert(session['email'], price_limit,item._id)
        alert.save_to_mongo()
    return render_template("alerts/new_alert.jinja2")

@UserDecorators.login_required
@alert_blueprint.route('/edit/<string:alert_id>', methods = ['POST', 'GET'])
def edit_alert(alert_id):
    alert = Alert.get_by_alert_id(alert_id)
    if request.method == 'POST':
        price = float(request.form['price_limit'])
        alert.price_limit = price
        alert.save_to_mongo()
        return redirect(url_for('users.user_alerts'))
    else:
        return render_template("alerts/edit_alert.jinja2",alert = alert)


@UserDecorators.login_required
@alert_blueprint.route('/deactivate/<string:alert_id>')
def deactivate_alert(alert_id):
    Alert.get_by_alert_id(alert_id).deactivate_alert()
    return redirect(url_for('users.user_alerts'))

@UserDecorators.login_required
@alert_blueprint.route('/activate/<string:alert_id>')
def activate_alert(alert_id):
    Alert.get_by_alert_id(alert_id).activate_alert()
    return redirect(url_for('users.user_alerts'))

@UserDecorators.login_required
@alert_blueprint.route('/delete/<string:alert_id>')
def delete_alert(alert_id):
    Alert.get_by_alert_id(alert_id).delete_alert()
    return redirect(url_for('users.user_alerts'))

@alert_blueprint.route('/<string:alert_id>')
@UserDecorators.login_required
def get_alert_page(alert_id):
    alert = Alert.get_by_alert_id(alert_id)
    return render_template("alerts/alert.jinja2", alert = alert)

@alert_blueprint.route('check_price/<string:alert_id>')
def check_alert_price(alert_id):
    Alert.get_by_alert_id(alert_id).load_item_price()
    return redirect(url_for('alerts.get_alert_page', alert_id = alert_id))

src/models/items/views.py
from flask import Blueprint

item_blueprint = Blueprint('items', __name__)

@item_blueprint.route('/item/<string:name>')
def item_page():
    pass

src/models/stores/views.py
from flask import Blueprint, render_template, request, json, redirect, url_for
from src.models.stores.store import Store
import src.models.users.decorators as User_Decorator

store_bluprint = Blueprint('stores', __name__)

@store_bluprint.route('/store/<string:store_id>')
def store_page(store_id):
    store = Store.get_by_id(store_id)
    return render_template("stores/store.jinja2", store = store)

@store_bluprint.route('/')
def index():
    stores = Store.find_all()
    return  render_template("stores/store_index.jinja2", stores = stores)

@store_bluprint.route('/new', methods=['POST','GET'])
@User_Decorator.admin_required
def create_store():
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag = request.form['tag']
        query = json.loads(request.form['query'])
        store = Store(name, url_prefix,tag,query)
        store.save_to_mongo()
        return redirect(url_for("stores.index"))
    return render_template("stores/create_store.jinja2")

@store_bluprint.route('/edit_store/<string:store_id>', methods = ['POST','GET'])
@User_Decorator.admin_required
def edit_store(store_id):
    store = Store.get_by_id(store_id)
    if request.method == 'POST':
        name = request.form['name']
        url_prefix = request.form['url_prefix']
        tag = request.form['tag']
        query = json.loads(request.form['query'])

        store.name = name
        store.url_prefix = url_prefix
        store.tag_name = tag
        store.query = query

        store.save_to_mongo()
        return redirect(url_for("stores.index"))
    else:
        return render_template("stores/edit_store.jinja2", store = store)

@store_bluprint.route('/delete_store/<string:store_id>')
@User_Decorator.admin_required
def delete_store(store_id):
    store = Store.get_by_id(store_id)
    store.remove()
    return redirect(url_for("stores.index"))

src/models/users/views.py
#blueprint
#endpoint of api that is related to the users
from flask import Blueprint, request, redirect, url_for, render_template, session
import src.models.users.erros as UserErrors
import src.models.users.decorators as UserDecorators


from src.models.users.user import User

user_blueprint = Blueprint('users', __name__)


@user_blueprint.route('/login', methods = ['POST', 'GET'])
def login_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        try:
            if User.is_login_valid(email, password):
                session['email'] = email
                return redirect(url_for('.user_alerts'))
        except UserErrors.UserError as e:
            return e.massage
    return render_template("users/login.jinja2")


@user_blueprint.route('/register',methods = ['POST', 'GET'])
def register_user():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        try:
            if User.register_user(email, password):
                session['email'] = email
                return redirect(url_for('.user_alerts'))
        except UserErrors.UserError as e:
            return e.massage
    return render_template("users/register.jinja2")

@user_blueprint.route('/alerts')
@UserDecorators.login_required
def user_alerts():
    user = User.get_by_email(session['email'])
    alerts = user.get_alerts()
    return render_template("users/alerts.jinja2", alerts = alerts)

@user_blueprint.route('/logout')
def logout_user():
    session['email'] = None
    return redirect(url_for('home'))

@user_blueprint.route('/check_alerts/<string:user_id>')
def check_user_alerts(user_id):
    pass

src/templates/alerts/alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>The Alert for {{ alert.item.name }} </h1>
    </div>
    <p> The price for the alert is {{ alert.price_limit }}</p>
    <p> The item was last checked on {{ alert.last_checked.strftime('%m-%d-%Y at %H:%M') }}</p>

    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-default" href = '{{ url_for('alerts.check_alert_price', alert_id = alert._id)}}'> Reload Price</a>
            <a class="btn btn-success" href = '{{ alert.item.url}}'> Visit item</a>
            <a class ="btn btn-default" href="{{ url_for('alerts.edit_alert',alert_id = alert._id)}}">Edit Alert </a>
            {% if alert.active %}
                <a class="btn btn-danger" href = '{{ url_for('alerts.deactivate_alert', alert_id = alert._id) }}'> Deactivate Alerts</a>
            {% else %}
                <a class="btn btn-success" href = '{{ url_for('alerts.activate_alert', alert_id = alert._id) }}'> Activate Alerts</a>
                <a class="btn btn-danger" href = '{{ url_for('alerts.delete_alert', alert_id = alert._id) }}'> Delete Alerts</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

src/templates/alerts/edit_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Edit Alerts
        </h1>
    </div>

    <div class="formgroup">
        <form method="POST">
            <div class="form-group">
                <label for="alert_name"> Alert Name</label>
                <input type="text" class="form-control" placeholder="Name" id="alert_name" , name="alert_name" disabled>
            </div>
            <div class="form-group">
                <label for="item_url"> Item URL</label>
                <input type="text" class="form-control" placeholder="http:://" id="item_url" , name="item_url" disabled>
            </div>
            <div class="form-group">
                <label for="price_limit"> Price_Limit</label>
                <input type="text" class="form-control" placeholder="45.00" value="{{ alert.price_limit }}" id="price_limit" , name="price_limit"
                       aria-describedby="descrip_block">
                <p id="descrip_block" class="help-block"> Your will receive email for the item under this price</p>
            </div>
            <button type="submit" class="btn btn-default navbar-btn">Update</button>
        </form>
    </div>
{% endblock %}

src/templates/alerts/new_alert.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Create Alerts
        </h1>
    </div>

    <div class="formgroup">
        <form method="POST">
            <div class="form-group">
                <label for="alert_name"> Alert Name</label>
                <input type="text" class="form-control" placeholder="Name" id="alert_name" , name="alert_name">
            </div>
            <div class="form-group">
                <label for="item_url"> Item URL</label>
                <input type="text" class="form-control" placeholder="http:://" id="item_url" , name="item_url">
            </div>
            <div class="form-group">
                <label for="price_limit"> Price_Limit</label>
                <input type="text" class="form-control" placeholder="45.00" id="price_limit" , name="price_limit"
                       aria-describedby="descrip_block">
                <p id="descrip_block" class="help-block"> Your will receive email for the item under this price</p>
            </div>
            <button type="submit" class="btn btn-default navbar-btn">Create</button>
        </form>
    </div>
{% endblock %}

src/templates/base.jinja2
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pricing Service</title>

    {% include 'html_dependencies.jinja2' %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home"></span> Pricing</a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#Navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="Navbar">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('stores.index') }}">Stores</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if session['email'] %}
                    <li><a href="{{ url_for('users.user_alerts') }}"><span class="glyphicon glyphicon-alert"></span> Your Alerts</a></li>
                    <li><a href="{{ url_for('users.logout_user') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                {% else %}
                    <li><a href="{{ url_for('users.register_user') }}"><span class="glyphicon glyphicon-user"></span> Sign up</a></li>
                    <li><a href="{{ url_for('users.login_user') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class ="content container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

src/templates/home.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="jumbotron">
        <h1>Pricing Service</h1>
        <p>Sign UP, and use it to check price for your dream items</p>
        <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register_user') }}" role="button">Sign Up</a></p>
    </div>
{% endblock %}

src/templates/html_dependencies.jinja2
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel ='stylesheet' href="{{url_for('static', filename = 'css/style.css')}}">
<!-- Latest compiled and minified JavaScript -->
<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

src/templates/stores/create_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">Create Store</div>

    <form method='POST'>
        <div class="form-group">
            <label for="name"> Store Name</label>
            <input type="text" class="form-control" placeholder="Store name" id="name" , name="name">
        </div>

        <div class="form-group">
            <label for="url_prefix"> URL prefix</label>
            <input type="text" class="form-control" placeholder="https://..." id="url_prefix" , name="url_prefix">
        </div>

        <div class="form-group">
            <label for="tag"> Tag name</label>
            <input type="text" class="form-control" placeholder="span" , value = "span" id="tag" , name="tag", aria-describedby="tag_help">
            <p id = "tag_help", class = "help-block"> You can get the tag by choose the price and right click and choose inspect</p>
        </div>

        <div class="form-group">
            <label for="query"> Query</label>
            <input type="text" class="form-control" placeholder='{ "id":"price"}' value='{ "id":"price"}' id="query" , name="query", aria-describedby="query_help">
            <p id = "queyhelp", class = "help-block"> You can get the query by choose the price and right click and choose inspect
            make sure use double quotation marks or it will fails</p>
        </div>

        <button type="submit" class="btn btn-default navbar-btn">Create</button>
    </form>
    </form>
{% endblock %}

src/templates/stores/edit_store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">Edit Store</div>

    <form method='POST'>
        <div class="form-group">
            <label for="name"> Store Name</label>
            <input type="text" class="form-control" placeholder="Store name" , value='{{ store.name }}' id="name" ,
                   name="name">
        </div>

        <div class="form-group">
            <label for="url_prefix"> URL prefix</label>
            <input type="text" class="form-control" placeholder="https://..." , value='{{ store.url_prefix }}'
                   id="url_prefix" , name="url_prefix">
        </div>

        <div class="form-group">
            <label for="tag"> Tag name</label>
            <input type="text" class="form-control" placeholder="span" , value='{{ store.tag_name }}' id="tag" ,
                   name="tag" , aria-describedby="tag_help">
            <p id="tag_help" , class="help-block"> You can get the tag by choose the price and right click and choose
                inspect</p>
        </div>

        <div class="form-group">
            <label for="query"> Query</label>
            <input type="text" class="form-control" placeholder='{ "id":"price"}' value='{{ store.query }}' id="query" ,
                   name="query" , aria-describedby="query_help">
            <p id="queyhelp" , class="help-block"> You can get the query by choose the price and right click and choose
                inspect
                make sure use double quotation marks or it will fails</p>
        </div>

        <button type="submit" class="btn btn-success navbar-btn">Update</button>
    </form>
    </form>
{% endblock %}

src/templates/stores/store.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1> Store {{ store.name }}</h1>
    </div>
    <p> All url in this store start with {{ store.url_prefix }}</p>

    {% if session['email'] in config.ADMINS %}
    <div class="panel panel-default">
        <div class="panel-body">
            <a class="btn btn-warning" href="{{ url_for("stores.edit_store", store_id = store._id) }}" , role="button">Edit Store</a>
            <a class="btn btn-danger" href="{{ url_for("stores.delete_store", store_id = store._id) }}" , role="button">Delete Store</a>
        </div>
    </div>
    {% endif %}
{% endblock %}

src/templates/stores/store_index.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page_header">
        <h1> List of Stores</h1>
    </div>
    <div class="list-group">
        {% for store in stores %}
            <a class="list-group-item" , href="{{ url_for('stores.store_page', store_id = store._id) }}">
                <h4> {{ store.name }}</h4>
                <p> The store with the url {{ store.url_prefix }}</p></a>
        {% endfor %}
    </div>
    {% if session['email'] in config.ADMINS %}
        <a class="btn btn-success" , href="{{ url_for('stores.create_store') }}">Create New</a>
    {% endif %}
{% endblock %}

src/templates/stores/store_list.jinja2
<div class="jumbotron">
    <h1>Nothing typed yet</h1>
</div>

src/templates/users/alerts.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="page-header">
        <h1>Your Alerts
            <small>a list of your alerts</small>
        </h1>
    </div>
    {% for alert in alerts %}
        <a class="list-group-item {{ 'list-group-item-warning' if not alert.active else '' }}" href="{{ url_for("alerts.get_alert_page", alert_id = alert._id) }}">
            {{ '<span class="glyphicon glyphicon-remove-circle" aria-hidden="true" ></span>' if not alert.active else '' }}
            <h4 class="list-group-item-heading">Alert for {{ alert.item.name }}</h4>
            <br class="list-group-item-text">Last Price Found
            <bold>{{ alert.item.price }}</bold>
            <br/>
            Last checked on
            <bold>{{ alert.last_checked.strftime("%d-%m-%Y at %H %M") }}</bold>
            </p>
        </a>
    {% endfor %}
    <a class = "btn btn-success" href = "{{ url_for("alerts.create_alert") }}"> Create New</a>
{% endblock %}

src/templates/users/login.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="formgroup">
        <form action = "{{ url_for('users.login_user') }}", method = "POST">
            <div class="form-group">
                <label for="email"> Email Address</label>
                <input type="email" class="form-control" placeholder="Email" id="email", name = "email">
            </div>

            <div class="form-group">
                <label for="password"> Password</label>
                <input type="password" class="form-control" placeholder="Password" id="password", name = "password">
            </div>
            <button type="submit" class="btn btn-default navbar-btn">Login</button>
        </form>
    </div>
{% endblock %}

src/templates/users/register.jinja2
{% extends "base.jinja2" %}
{% block content %}
    <div class="formgroup">
        <form method = "POST">
            <div class="form-group">
                <label for="email"> Email Address</label>
                <input type="email" class="form-control" placeholder="Email" id="email", name = "email">
            </div>

            <div class="form-group">
                <label for="password"> Password</label>
                <input type="password" class="form-control" placeholder="Password" id="password", name = "password">
            </div>
            <button type="submit" class="btn btn-default navbar-btn">Register</button>
        </form>
    </div>
{% endblock %}